Intro
=====

This set of ansible playbooks is intended for install of OpenShift-Origin on RHEL  platform. 
It draws heavily on ansible-examples/openshift and ansible-openshift_origin, in fact probably 90% of code comes from either of the two. 

Reason for this playbook existence is that ansible-openshift_origin is Fedora-centric and single-host at the moment, and ansible-examples/openshift is geared for HA multihost deployment. This playbook is more of variation from ansible-openshift_origin with bit more multihost and RHEL goodness from ansible-examples/openshift

Licenses
========

* `ansible-openshift_origin 

  * `Apache 2.0 <http://www.apache.org/licenses/LICENSE-2.0>`_

* `ansible-examples/openshift <https://github.com/ansible/ansible-examples/tree/master/openshift>`_

  * `Creative Commons Attribution 3.0 Unported License <http://creativecommons.org/licenses/by/3.0/deed.en_US>`_

* This code

  * `GPL v3 <http://www.gnu.org/licenses/gpl-3.0.txt>`_

Use
===

There are two stages for deployment: install and setup. You should run appropriate playbooks in that order::

  # ansible-playbook -i inventory.txt install-yum.yml
  # ansible-playbook -i inventory.txt setup.yml

Note that you can use install-*.yml script that matches your desired implementation. Yum is default method of deployment but others should be available (or not so hard to derive from install-yum.yml)

Dependencies
============

* `ansible-libs <https://github.com/droopy4096/ansible-libs>`_
 
  * rpm_query module is required by this reworked modular implementation

Requirements
============

* / - 1G+
* /usr - 1.5G+
* /var - 2G+


Development
===========

to ignore changes made locally to ansible.cfg (thus never commiting them back)::

  $ git update-index --assume-unchanged ansible.cfg

to resume tracking::

  $ git update-index --no-assume-unchanged ansible.cfg


ActiveMQ
========

Test ActiveMQ:

First, connect from your workstation and forward ports, like so::

  $ ssh -L 8161:localhost:8161 root@broker.some.net

Now point your browser to::

  http://localhost:8161/admin/network.jsp

By default use credentials::

  admin:admin
