---

- hosts: all
  roles: 
  - role: common/setup

- hosts: dns
  roles: 
  - role: dns/setup

- hosts: mongodb
  roles: 
  - role: mongodb/setup

- hosts: mq
  roles: 
    - role: qpid/setup
      when: mq_provider == "qpid"
    - role: activemq/setup
      when: mq_provider == "activemq"

- hosts: broker
  roles:
  - role: mcollective-client/setup
  - role: broker/setup
  # - role: broker-plugins
  - role: web-console/setup

- hosts: node
  roles:
  - role: node/setup

### Cut-off

- hosts: all
  roles: 
    - role: post-deploy/setup

