---
### main.yml - mcollective-client role for an OpenShift Origin deployment 
#
# Ansible playbook to deploy OpenShift Origin using nightly builds
#


- name: Create mcollective client config directory
  tags: configure
  file: dest=/opt/rh/ruby193/root/etc/mcollective state=directory

- name: Configure mcollective client
  tags: configure
  template: src=client.cfg.j2 dest=/opt/rh/ruby193/root/etc/mcollective/client.cfg
            owner=root group=root mode=0644 backup=yes
