---
### main.yml - console role for an OpenShift Origin deployment 
#
# Ansible playbook to deploy OpenShift Origin using nightly builds
#

- name: Configure Persistent FirewallD for http console
  shell: lokkit --service http
- name: Configure Persistent FirewallD for https console
  shell: lokkit --service https

- name: Ensure Install - console pkgs
  rpm_query: pkg={{item}} state=present
  with_items:
    - rubygem-openshift-origin-console
    - gcc
    - make
    - openshift-origin-console

#FIXME - Should parameterize this later to allow for setup of different auth
- name: Configure Basic Auth
  template: src=auth-remote-user-basic.conf.j2
            dest=/var/www/openshift/console/httpd/conf.d/openshift-origin-auth-remote-user-basic.conf
            owner=apache group=apache mode=0640 backup=yes

- name: Configure Demo user with htpasswd
  copy: src=console_htpasswd dest=/etc/openshift/htpasswd
        owner=apache group=apache mode=0640 backup=yes

- name: Configure OpenShift Origin Console
  template: src=console.conf.j2 dest={{console_conf_path}}
            owner=apache group=apache mode=0644 backup=yes
  notify: restart console

- name: Bundle install and build Rails assets
  script: console_bundle_install.sh
  notify: restart console
  environment: proxy_settings

- name: SELinux settings for OpenShift Origin Console
  seboolean:  name={{item}} state=true persistent=yes
  with_items:
   - httpd_can_network_connect
   - httpd_can_network_relay
   - httpd_read_user_content
   - httpd_enable_homedirs
   - httpd_execmem

- name: start and enable openshift-console
  service: name=openshift-console state=started enabled=yes
