---
### main.yml - post-deploy role for an OpenShift Origin deployment 
#
# Ansible playbook to deploy OpenShift Origin using nightly builds
#

# Set resolv.conf
- name: Set resolv.conf
  tags: configure
  template: src=resolv.conf.j2
            dest=/etc/resolv.conf
